language: java
jdk:
- oraclejdk8
before_install:
- mvn install:install-file -Dfile=./local-repo/org/graphstream/gs-algo/2.0.0-SNAPSHOT/gs-algo-2.0.0-SNAPSHOT.jar
  -DgroupId=org.graphstream -DartifactId=gs-algo -Dversion=2.0.0-SNAPSHOT -Dpackaging=jar
- mvn install:install-file -Dfile=./local-repo/org/graphstream/gs-core/2.0.0-SNAPSHOT/gs-core-2.0.0-SNAPSHOT.jar
  -DgroupId=org.graphstream -DartifactId=gs-core -Dversion=2.0.0-SNAPSHOT -Dpackaging=jar
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
deploy:
  provider: releases
  api_key:
    secure: FkPhKjSlh3DAF3dB+g07N+30/VeqtZBp40jsbR/K6W4RiG80iD6pDyDBJhF6+2LFzNAMNEdLym2xUBgBcwv9UANoq6GNqVCxSStMJS/fupNeabkZfa29mSTp7DxY3BPPNrFFLqDZYluo2LWTvlenzGaBy/c2oRCop5WTVAQkdAbgJC5myOgrGtY9MxZWiqFUFOaFUSO4HGX6geEDVR5iTBkZnxdM9yWMTSZgZAsORBC9V9o40B6oXEnUpofn0s7mAuJnAy2uj0zWgw5xV37iUlfEO1BvoC6L1aisK1qWBaPmMbu0YphiNHNRZh2wLI9HhAS9rkvf8ocpJUPwMiUW61gjASZqewu0kqnTRi7tREOFQmsoOVk6yxPH1FPc6GlYHk/qDY0N8e0yscNIMfx8PTKnY8CW4KmBm+LZ5Dd42Bbh4+VG2vAdGXboXg8KGqCg+LWxQKDATyaMBWQqWRcMFurDKnv9mIpL5sBM3Q7H2RsKemnzfV1+zT7QBOYQkRX1ZlRPKVmXxGnsmwxVezqlr7kf7uVDiwkkMJMvy+2zbZNGqssT7Xkaoq2LLZ8JnRq3YTG6xPbCdH/DHhw12cR2qQbxL4ak1DUi+f/qZFrzXJmuFHYR4TsR+z3B2yJHf7jAuBsUmnvGo8OtdES9Q9HU5yywLgoLIlSr3v6t7GcDozQ=
  file_glob: true
  file: target/hp2sat-*
  skip_cleanup: true
  on:
    repo: amjadKhalifah/HP2SAT1.0
    tags: true
