package de.tum.in.i4.hp2sat.causality;

public enum SolvingStrategy {
    BRUTE_FORCE, BRUTE_FORCE_OPTIMIZED_W, SAT, SAT_MINIMAL, SAT_COMBINED, SAT_COMBINED_MINIMAL, SAT_OPTIMIZED_W,
    SAT_OPTIMIZED_W_MINIMAL, SAT_OPTIMIZED_FORMULAS, SAT_OPTIMIZED_FORMULAS_MINIMAL, SAT_OPTIMIZED_AC3,
    SAT_OPTIMIZED_AC3_MINIMAL, ILP, MAX_SAT, ILP_WHY
}
